# Generated by Django 4.1.7 on 2023-08-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_info_age_info_department_info_name_info_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
    ]
